- name: Install common dependencies
  hosts: work_machine
  become: yes
  tasks:
    - name: "Common - System"
      package:
        name: 
          - systemd # in case some stuff like machinectl is missing
        state: present
    - name: "Common - General dev/build deps"
      package:
        name: 
          - make
          - cmake
          - gcc
        state: present
    - name: "Common - Alacritty (lightweight terminal emulator)"
      include_tasks: 
        file: "{{ item }}"
      with_first_found:
        - files:
          - "tasks/{{ansible_distribution}}/install-alacritty.yaml"
          - "tasks/{{ansible_os_family}}/install-alacritty.yaml"
          - "tasks/default/install-alacritty.yaml"
    - name: "Common - Terminal Utilities"
      package:
        name: 
          - zsh
          - tmux
          - vim
          - fzf
          - xsel
        state: present
    - name: "Common - Python"
      package:
        name: 
          - python
          - python-pip
        state: present
    - name: "Common - File manager"
      package:
        name: 
          - thunar
        state: present
