- hosts: work_machine
  become: false
  tasks:
    - name: user
      debug: msg="{{ansible_user_id}}"
    - name: architecture
      debug: msg="{{ansible_architecture}}"
    - name: architecture alt
      debug: msg="{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
    - name: distribution
      debug: msg="{{ansible_distribution}}"
    - name: os_family
      debug: msg="{{ansible_os_family}}"
    - name: HOME
      debug: msg="{{ansible_env.HOME}}"
    - name: ansible_user_id
      debug: msg="{{ansible_user_id}}"
