- hosts: work_machine
  become: false
  tasks:
    - name: distribution
      debug: msg="{{ansible_distribution}}"
    - name: os_family
      debug: msg="{{ansible_os_family}}"
    - name: HOME
      debug: msg="{{ansible_env.HOME}}"
    - name: ansible_user_id
      debug: msg="{{ansible_user_id}}"
