- name: "Home config - OS specific packages"
  import_playbook: "./os-specific.yaml"
  vars:
    tasks:
      - chezmoi
- name: Configure ~ env
  hosts: work_machine
  become: no
  tasks:
  - name: "Home config - setup chezmoi"
    shell: chezmoi init --apply --force --ssh le-quentin
    args:
      creates: "{{ansible_env.HOME}}/.local/share/chezmoi"
  - name: "Home config - zsh by default"
    become: yes
    shell: chsh -s /usr/bin/zsh {{ ansible_user_id }}
    register: chsh_result
    changed_when: "'Shell changed' in chsh_result.stdout"
    # TODO notify to ask for relogin on change
  - name: "Home config - fzf - clone"
    git: 
      repo: https://github.com/junegunn/fzf.git
      depth: 1
      dest: "{{ansible_env.HOME}}/.fzf"
      update: no
  - name: "Home config - oh-my-zsh"
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" "--unattended"
    args:
      creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  - name: "Home config - oh-my-zsh - restore zshrc"
    shell: "mv {{ansible_env.HOME}}/.zshrc.pre-oh-my-zsh {{ansible_env.HOME}}/.zshrc"
    args:
      removes: "{{ansible_env.HOME}}/.zshrc.pre-oh-my-zsh"
  - name: "Home config - powerlevel10k"
    git:
      repo: https://github.com/romkatv/powerlevel10k.git
      depth: 1
      dest: "{{ansible_env.HOME}}/.oh-my-zsh/custom/themes/powerlevel10k"
      update: no
  - name: "Home config - tmux-powerline"
    git:
      repo: https://github.com/erikw/tmux-powerline.git
      depth: 1
      version: 42f06c1
      dest: "{{ansible_env.HOME}}/.tmux-powerline"
      update: no
  - name: "Home config - install fonts"
    become: yes
    copy:
      src: ./fonts/ 
      dest: /usr/local/share/fonts/
  - name: "Home config - reload fonts cache"
    shell: fc-cache -f -v
- name: "Home config - OS specific config"
  import_playbook: "./os-specific.yaml"
  vars:
    tasks:
      - fzf
