- name: "Neovim - OS specific dependencies"
  become: yes
  import_playbook: "./os-specific.yaml"
  vars:
    tasks:
      - fd-find
- name: Install and setup neovim with plugins
  hosts: work_machine
  become: no
  tasks:
    - name: "Neovim - dependencies"
      become: yes
      package:
        name: 
          - ripgrep
        state: present
    - name: "Neovim - Install"
      become: yes
      package:
        name: 
          - neovim
        state: present
    - name: "Neovim - create plug.vim directory"
      file:
        path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
        state: directory
    - name: "Neovim - install plug.vim"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
    - name: "Neovim - install plugins"
      shell: nvim -u ~/.config/nvim/init.vim --headless -ce "PlugInstall" -c "qa"
      args:
        executable: /bin/bash
