- name: "Neovim - Common dependencies" 
  hosts: work_machine
  become: no
  tasks:
    - name: "Neovim - dependencies"
      become: yes
      package:
        name: 
          - ripgrep
          - python-pynvim
        state: present
- name: "Neovim - npm dependencies"
  hosts: work_machine
  become: yes
  tasks:
    - name: "Neovim - npm neovim"
      shell: "npm -g install neovim"
      args:
        creates: "/lib/node_modules/neovim"
- name: "Neovim - OS specific install"
  become: no
  import_playbook: "./os-specific.yaml"
  vars:
    tasks:
      - fd-find
      - neovim
- name: "Neovim - Plugins" 
  hosts: work_machine
  become: no
  tasks:
    - name: "Neovim - create plug.vim directory"
      file:
        path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
        state: directory
    - name: "Neovim - install plug.vim"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
    - name: "Neovim - install plugins"
      shell: nvim -u ~/.config/nvim/init.vim --headless -ce "PlugInstall" -c "qa"
      args:
        executable: /bin/bash
    - name: "Neovim - install vscode-js-debug, for node debug"
      shell: install-vscode-js-debug
      args:
        creates: "{{ ansible_env.HOME }}/.local/share/vscode-js-debug/out/LICENSE"
