- name: "Default - asdf - clone repository"
  become: yes
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "/opt/asdf-vm"
    refspec: v0.14.0
    update: no
# That's it, .zshrc addition handled by chezmoi!
