- name: "Home config - fzf - build"
  shell: ".fzf/install --no-key-bindings --no-completion --no-update-rc" # Install because some distros have it outdated - not updating any files because managed by chezmoi
  args:
    creates: "{{ ansible_env.HOME }}/.fzf/bin/fzf"
- name: "Home config - fzf - (re)install"
  file:
    src: "{{ ansible_env.HOME }}/.fzf/bin/fzf"
    dest: /usr/bin/fzf
    state: link
